version: "{build}"
clone_depth: 1
platform:
    - x64
    - x86

install:
    - nuget install sqlite
    - gem install yard rake test-unit rdoc 
    - gem install escape log4r json sequel
    - gem install sqlite3

build_script:
    - rake
    
artifacts:
    # The gem for deployment
    - path: \*.gem
    
    # API Docs
    - path: doc
    
    # Test coverage
    - path: coverage
    
