version: "{build}"
clone_depth: 1
platform:
    - x64
    - x86
install:
#    - choco install SQLite
#    - Install-Package sqlite
    - nuget install sqlite
    - install-gems.bat
build_script:
    - rake
#artifacts:
#    - path: *.gem
